### ISSUE TITLE
What causes time difference?

### ISSUE THREAD

**Issue by FoxxMD** [jamesrom/jamesrom.github.io#36]
Right now its at -6,633ms...6 seconds of time difference. But what is it a difference of? Is that coming from the websocket data from reddit? Like, everyone is behind -6.6 seconds? Or just uniquely this app? If it's the app, what causes that?

**Comment by lezed1** [comment]
I've actually wondered this myself, so I just looked through the code for you! Here is the relevant line: https://github.com/jamesrom/jamesrom.github.io/blob/54f6fe5696ffaaf9da842d4267970d93416576d4/comms.js#L49

It appears that each time-stamped (denoted by the "now_str" key) in the tick event sent via Reddit's WebSocket. The "Time Difference" (internally reffered to as "lag") is calculated by taking the calculating the difference between the sent time and the current time.

To answer your question directly, it is you that is behind 6.6. This could be caused by your computer's clock being out of sync from Reddit's, or network load or just latency.

**Comment by FoxxMD** [comment]
Thanks for the explanation! I wonder how Reddit's servers deal with this discrepancy when you send a click for the button. [Someone thinks they are using an hmac](https://www.reddit.com/r/webdev/comments/313531/rthebutton_using_secure_websockets/cpygih4) of which one of the hash components is the timestamp. If my os clock is off, or network latency is bad does Reddit use their server's time instead?

**Comment by lezed1** [comment]
I believe this is how you get the cheater flair. It looks just like purple, but the tag's HTML class is different.
